### ISSUE TITLE
META: Next Major Version (Taurus)

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#15]
These issues need to be sorted before we can release Taurus.
## Python Wrapper
- [x] #6 Abstract Wrapper
- [x] #21 Implement PEP8 Coding Style
## PHP Wrapper
- [x] #12 Gatekeeper calls in PHP
- [x] #13 Registry functions in PHP
- [x] #19 PHP Tests
- [x] #26 Extra Newlines in Logging Function
## Ruby Wrapper
- [x] #7 Gem Paths
- [x] #23 Test Connectivity
- [x] #22 Wrapper / Installation
- [x] #17 Coding Style
## Bash Wrapper
- [x] #16 Bash Coding Style
## All
- [x] #8 System Icon Font 
## Supporting Assets
- [x] #10 Create Documentation
- [x] #9 Create Tests
- [x] #11 Fallback server for icons
## Meta Structure
- [x] #14 JSON Structure

**Comment by shawnrice** [comment]
Let's track the development status here [on the wiki](https://github.com/shawnrice/alfred-bundler/wiki/Taurus-Development-Status) instead of this issue.
