### ISSUE TITLE
PHP Bundler TODO

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#50]
Let's track this...
- [x] #19 PHP Tests
- [x] #12 fix Gatekeeper calls
- [x] #13 integrate registry functions
- [x] #26 PHP files creates new logs
- [x] #8 system icons
- [x] #45 color caching
- [x] #46 wrappers (formerly: bindings)
- [x] #49 applescript install message
- [x] #44 environmental variables
- [x] #30 argument load order
- [x] #32 notify function
- [x] #37 logging standards
- [x] #42 better error handling

**Comment by deanishe** [comment]
I've had a little fiddle wrt #44 so installations succeed, but something still isn't working quite as expected. I haven't been able to track it down yet. Try creating another branch and setting that as active via `ALFRED_BUNDLER_DEVEL` and see if you can track down the problem.

**Comment by shawnrice** [comment]
Okay. Looks like I just need to finish the tests and finish up #33, #12, #34.

**Comment by shawnrice** [comment]
Finished #33, #12, and #34.

**Comment by shawnrice** [comment]
I added a checklist to issue #60 about creating tests, so, since the PHP tests are the only thing left on here, I'm closing the issue.
