### ISSUE TITLE
Python TODO

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alfred-bundler#61]
A consolidated list of stuff that needs to be done in the Python bundler:
- [x] Allow `alter` argument to `icon()` to be an alternative colour, not just a boolean flag (?)
- [x] Get bundle ID from environmental variables if available (fall back to `info.plist`)
- [x] Create interface to `wrappers` (formerly `bindings`) #46 
  - Just import them into the `bundler` namespace or add utility methods like, err, `utility()`?
- [x] Use `cocoaDialog` wrapper to implement `bundler.notify()` (?)
- [x] Multiple icon servers
- [x] Multiple install servers (Bitbucket and GitHub)
- [ ] Common cross-bundler caches
  - [x] Colours
  - [x] Utilities
  - ???
- [x] .icns conversion
- [ ] Standard, cross-bundler way to generate documentation #10 
- [x] Pre-installation notification #49
- [x] Installation errors #63
- [ ] Unit tests #80
- [ ] Documentation #81
- [ ] Demo workflow no longer works #82

**Comment by shawnrice** [comment]
#63 ?
