### ISSUE TITLE
META: Bundler Tracking

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#65]
So, here's the ultimate issue for Taurus. These should be checked off as the code is done and ready for release. Ultimately, this should be the last issue closed for the milestone "Taurus."
### Bundler Code Status (checked means done)
- [x] Bash
- [x] PHP
- [ ] Python
- [x] Ruby
- [x] Applescript
### Bundler Test Status (checked means 100% coverage)
- [x] Bash
- [x] PHP
- [ ] Python
- [x] Ruby
- [x] Applescript
### Reviewed and Ready (means, we're ready to launch)
- [ ] Bash
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Applescript
### General
- [ ] Maintenance script
### Documentation
- [ ] General
  - [ ] For Users
  - [ ] Wrappers
  - [ ] For Workflow Authors
    - [x] For Bash
    - [x] For PHP
    - [ ] For Python
    - [x] For Ruby
    - [x] Applescript
  - [ ] For Developers
    - [x] For Bash
    - [x] For PHP
    - [ ] For Python
    - [x] For Ruby
    - [x] Applescript
- [ ] API Documentation
  - [x] For Bash
  - [x] For PHP
  - [ ] For Python
  - [x] For Ruby
  - [ ] Applescript
### Before Release
- [ ] Check for and remove any testing code
- [ ] Check auto-update functionality
- [ ] Sync new Taurus branch
- [ ] Change all instances of `devel` to `taurus`
- [ ] Remove documentation and tests from Taurus branch
- [ ] double-check in-file documentation for completeness
- [ ] Tag Taurus-1 and Taurus-latest
- [ ] push bundler-docs to this repo's GH pages
- [ ] update 'more info' button in AS install confirmation to gh-pages
- [ ] update README.md
- [ ] run tests one last time
### Release
- [ ] New forum thread
- [ ] clean issue queue
- [ ] upload example workflow

Update and release our new workflows (or at least the ones that I already use the bundler in).

**Comment by shawnrice** [comment]
Note: not **all** of the documentation above needs to be perfect, but we need to have enough to tell users what is going on and to tell workflow authors how to implement the damn thing with at least a few examples.

**Comment by deanishe** [comment]
Should there also be a demo workflow for each language?

I have a very heavily commented Python one for Taurus (as well as the Aries one that's on Packal) that shows how to use icons, utilities and icons.

Test coverage is, AFAIK, still 100% for Python, and the API is very well documented within the source code (in Sphinx format, so it can extracted relatively easily).

So, I'd say the tests and docs for Python are close to complete. There should probably be one more help file giving an overview and a few code examples, and linking to the demo workflow.

The problem is, as before, compiling all the docs into one consistent format :(

**Comment by shawnrice** [comment]
The consistent format is still the problem. Worst case: we just load all API documentation in an iFrame of the bundler help pages. Since the display of the documentation isn't tied to any bundler minor version, we can update it if we find a better way later without having to update the bundlers themselves. I'm actually thinking that we just embrace this "worst case" for now.

The PHP source is heavily documented as well. I need to go back through and make sure that it's completely complete (yes, the redundancy is good), and it can easily be extracted with a number of doc generators.

We might need to write the API docs for Bash manually. Sucks. Or we could leave them out for now.

Test coverage for Bash is 100%, but it doesn't work with any particular testing framework. The only tests that fail in the Bash fail sporadically due to rounding errors, basically. But the rounding errors occur in the 9th or 10th decimal. You should run the tests for fun, and you should see if they can be improved.

Where is the code for the example workflow for Taurus? I can contribute code that duplicates examples using the PHP and Bash bundlers. Maybe the Ruby one shortly. We should have all the examples in one workflow rather than three or four.

We do need to write the "general" documentation. Some of it is one the wiki and should be ported. 

There should be example code for each implementation that illustrates all the functionality. (Loading, Logging, Icons). We also need to link to the icon server.

Since `gh-pages` uses Jekyll, we can write these in Markdown. I started playing around with the design of the new docs for Taurus, which would be a Jekyll template, but still working on that.

**Comment by deanishe** [comment]
I haven't uploaded the demo workflow code anywhere yet, as the whole thing is still in flux.

I was going to upload it now, but `AlfredBundler.py` is currently borked :unamused: 

@Ritashugisha: great work with the updates, but can you try to keep the tests up-to-date with changes to the code and make sure they're passing before commiting? `AlfredBundler.py` is currently borked, as `notify()` is gone but still used in `init()`.

d1f8b60 is the best commit message :laughing:

**Comment by shawnrice** [comment]
> d1f8b60 is the best commit message :laughing:

Yup. I've made sure that I've run the tests each time after that before pushing...

My bad.

**Comment by shawnrice** [comment]
Can you just describe what you showcase in the workflow?

**Comment by deanishe** [comment]
It does the same as [the Aries one](http://www.packal.org/workflow/alfred-dependency-bundler-demo-python).

It shows a bunch of random icons in random colours, uses Pashau to allow the user to change the colour, and shows the current time in a bunch of random timezones (using an external library installed by the bundler).

That is to say, it demos using icons, utilities and Python dependencies. It contains [enormous amounts of comments](https://github.com/deanishe/alfred-bundler-python-demo/blob/master/src/demo.py).

**Comment by stephen-bunn** [comment]
I'll try to get the Python version of the bundler unborked either later today or tomorrow.

Sorry bout' that :(

**Comment by deanishe** [comment]
No hurry. Love the install dialog box.

**Comment by shawnrice** [comment]
I wrote the Bash API documentation by hand since we couldn't settle on a good generator. @smargh: Should the same be done for AppleScript?

**Comment by shawnrice** [comment]
We're getting close, guys. The "milestone" Taurus is at 80%. The AS, Bash, PHP, and Ruby bundlers seem to be working. Most of the documentation has been written. I think that most everything is covered by tests...

**Comment by deanishe** [comment]
We're back to square one now wrt Python tests and docs. Also the demo workflow won't work with the rewrite f235392a66cf8bcfac1d20dc7b2ff0688ab78634.

The more I think about it, the more I think there should be 1.5 sets of docs for each bundler. One general set on the bundler website and, if appropriate, a second language-specific version.

Certainly, I think it makes sense to have separate API docsets for each bundler, which we could (hopefully) generate automatically from the source.

**Comment by shawnrice** [comment]
Isn't that what we already have?

[Here's the current build of the bundler documentation](https://shawnrice.github.io/bundler-docs/). The "quickstart" seems to be the general, language specific implementation, and the "documentation" is the auto-generated sets.

**Comment by shawnrice** [comment]
So, for the auto-generated sets:
- AppleScript doesn't exist.
- Bash had to be done by hand (and has been).
- PHP is generated by ApiGen.
- Ruby is generated by yardoc.
- Python will be generated by Sphinx.

**Comment by deanishe** [comment]
The general docs are lovely (what did you build them with?)

Having a Quickstart and perhaps a tutorial or two up there is, imo, the right way to go.

The individual bundlers do have different APIs, however, and the language-specific doc generation tools have some features that are too good to miss. I think Sphinx is the way to go with Python, but I'm unfamiliar with the tools available for the other languages. IIRC, we failed to find a tool that worked well for PHP, Python and Ruby.

I've been using the [Read the Docs](https://readthedocs.org/) theme with [Alfred-Workflow](http://www.deanishe.net/alfred-workflow/), and find it pretty good.

**Comment by shawnrice** [comment]
The docs are just written by hand and built on Foundation 5 (similar to Bootstrap, but I like it better).

Do we need more of a quickstart than the quickstarts that are already up there? For instance, look at the [PHP quickstart](https://shawnrice.github.io/bundler-docs/quickstart-php.html). If I remember correctly — it's been a while since I was working on these — that one has everything on it, and we need to catch the others up to it. It tells you how to do pretty much everything you need with the bundler, and it then refers you to the docs for more.

Obviously, all the docs will have to be updated when we change the definition of `latest`.

A tutorial might be cool. Not sure how to go about that though. Do we write one for each language? If so, are they real workflows or would the tutorial just go about explaining the "example" workflow?

**Comment by shawnrice** [comment]
And, yes, it was just too hard to get a single doc generator to generate all, so I just picked them per language and used a decent theme, but that's also why the documentation opens in a separate window.

The Sphinx theme that you use with Alfred-Workflow is pretty. I'm all about using it.
