### ISSUE TITLE
Ruby Bundler TODO

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#66]
The most neglected of the bundlers....
- [x] Bundler
  - [x] Icons
    - [x] Update Color Conversion methods
    - [x] Background for ENV
    - [x] Background for utility
    - [x] ...
  - [x] Gems
    - [x] Check gem loading paths: #7 
  - [x] Logging
    - [x] User facing log #39 
    - [x] Logging standards #37 
    - [x] Refactor logging functions to consolidate
  - [x] Wrappers
  - [x] Generic load function
  - [x] Utilities
- [x] Bundlet
  - [x] Install Method ( #22 )
  - [x] Add in better error checking for install method
  - [x] Applescript Dialog

Probably more....

**Comment by shawnrice** [comment]
Development on branch `ruby-dev` for this

**Comment by shawnrice** [comment]
Merged `ruby-dev` back into `devel`

**Comment by shawnrice** [comment]
Okay. So this thing is written... I think. I need to go back through and make sure that **everything** is there. Basically, I need to write some tests. And I need to document.

I also need to fiddle more with the `notify` function, but all functionality **should** be there.

**Comment by shawnrice** [comment]
Closing. Now just dealing with tests and any bug fixes that come up.
